// <auto-generated />
#nullable disable

namespace Stuntman.Web.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

        modelBuilder.Entity("Stuntman.Shared.Models.ContractModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ContractGuid")
                    .HasColumnType("TEXT");

                b.Property<string>("CostCenter")
                    .HasColumnType("TEXT");

                b.Property<string>("Department")
                    .HasColumnType("TEXT");

                b.Property<int>("DepartmentExternalId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("TEXT");

                b.Property<int>("HoursPerWeek")
                    .HasColumnType("INTEGER");

                b.Property<int>("IsManager")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("TEXT");

                b.Property<int?>("StuntmanModelId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.Property<string>("UserExternalId")
                    .HasColumnType("TEXT");

                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("StuntmanModelId");

                b.ToTable("Contracts");
            });

        modelBuilder.Entity("Stuntman.Shared.Models.DepartmentModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("DisplayName")
                    .HasColumnType("TEXT");

                b.Property<int>("ExternalId")
                    .HasColumnType("INTEGER");

                b.Property<string>("ManagerExternalId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Departments");
            });

        modelBuilder.Entity("Stuntman.Shared.Models.StuntmanModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("TEXT");

                b.Property<string>("BirthPlace")
                    .HasColumnType("TEXT");

                b.Property<string>("BusinessEmailAddress")
                    .HasColumnType("TEXT");

                b.Property<string>("BusinessPhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<string>("City")
                    .HasColumnType("TEXT");

                b.Property<string>("Company")
                    .HasColumnType("TEXT");

                b.Property<string>("DisplayName")
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalId")
                    .HasColumnType("TEXT");

                b.Property<string>("FamilyName")
                    .HasColumnType("TEXT");

                b.Property<string>("GivenName")
                    .HasColumnType("TEXT");

                b.Property<int>("HouseNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("Initials")
                    .HasColumnType("TEXT");

                b.Property<int>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("Language")
                    .HasColumnType("TEXT");

                b.Property<string>("PersonalEmailAddress")
                    .HasColumnType("TEXT");

                b.Property<string>("PersonalPhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<string>("Street")
                    .HasColumnType("TEXT");

                b.Property<string>("UserGuid")
                    .HasColumnType("TEXT");

                b.Property<int>("UserId")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserName")
                    .HasColumnType("TEXT");

                b.Property<string>("ZipCode")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Stuntman");
            });

        modelBuilder.Entity("Stuntman.Shared.Models.ContractModel", b =>
            {
                b.HasOne("Stuntman.Shared.Models.StuntmanModel", null)
                    .WithMany("Contracts")
                    .HasForeignKey("StuntmanModelId");
            });

        modelBuilder.Entity("Stuntman.Shared.Models.StuntmanModel", b =>
            {
                b.Navigation("Contracts");
            });
#pragma warning restore 612, 618
    }
}
